### ISSUE TITLE
Addition of quaternion tensor and real tensor fails

### ISSUE THREAD

**Issue by sscardapane** [ispamm/hTorch#1]
Adding a quaternion-valued tensor to a real-valued tensor fails:

`quaternion.QuaternionTensor(torch.rand(2, 4)) + torch.rand(2)`

Currently, it fails with this error message:

![image](https://user-images.githubusercontent.com/39627140/108699511-9fba3900-7505-11eb-90a6-8670c8334f39.png)

**Comment by giorgiozannini** [comment]
Fixed scalar/quaternion addition to properly add the scalar to the real part of the quaternion only.
