### ISSUE TITLE
QBatchNorm2d calculation

### ISSUE THREAD

**Issue by akudan** [ispamm/hTorch#5]
Hi, I was looking at your QBatchNorm2d code and attempting to fix some of the issues. I noticed you use the pseudo-covariance directly for normalization, rather than variance which is more typical; I was wondering if you could provide a link to the relevant literature on this method of normalization since I'm unfamiliar with it. Thanks!

**Comment by giorgiozannini** [comment]
Thanks for the interest in our work!
`QBatchNorm2d` is based on the following paper by Chase J. Gaudet et al.: [paper](https://arxiv.org/pdf/1712.04604.pdf)

**Comment by akudan** [comment]
Thanks for your reply! You've done some great work. I actually found that paper but I was having trouble aligning the calculations in the paper with your code -- in your code you use the Cholesky upper triangular whereas in the paper it seems to use the lower (perhaps the difference doesn't matter). Also, in the paper it seems to say that W is calculated from Cov<sup>-1</sup>, and in your code it is calculated from Cov. I wonder if it would be possible to add some additional code comments or commentary here. Thanks!

**Comment by giorgiozannini** [comment]
There is indeed some confusion in the code:
`self.inverse_sq_cov` should actually be called `self.sq_cov` as you rightly pointed out. The use of upper or lower traingular should have no impact on the result. Thanks again and please if there is anything else that doesn't sound quite right let us know!

**Comment by giorgiozannini** [comment]
There is indeed some confusion in the code:
`self.running_invsq_cov` should be `self.running_sq_cov`. Thanks for pointing it out!
With regards to the computation: we do calculate the Cholesky of not inverted `cov`. Please keep in mind that the Cholesky of the inverse covariance matrix is just inverse of the Cholesky of the not inverted one [https://math.stackexchange.com/questions/712993/cholesky-decomposition-of-the-inverse-of-a-matrix](url). Then the `triangular_solve` takes as input `b` and `A` referring to the following linear system: `AX = b` meaning that it does not require the inverted version of `b` (the Cholesky of the not inverted covariance matrix) to solve it [https://pytorch.org/docs/stable/generated/torch.triangular_solve.html](url). 
Thanks again and please if anything doesn't sound quite right let us know!

**Comment by giorgiozannini** [comment]
Although there was a mistake on not calculating the cholesky if the model is in `eval` mode. We fixed it, changed variable names and added reference to original code of `cplxmodule`!
